# $Id: Makefile,v 1.14 2008/04/04 02:01:01 mascarenhas Exp $

#include config

install:
	IF NOT EXIST "$(LUA_LUADIR)" mkdir "$(LUA_LUADIR)"
	IF NOT EXIST "$(LUA_LUADIR)/socket-io" mkdir "$(LUA_LUADIR)/socket-io"
	IF NOT EXIST "$(LUA_LUADIR)/socket-io/socket.io-client" mkdir "$(LUA_LUADIR)/socket-io/socket.io-client"
	xcopy socket-io "$(LUA_LUADIR)/socket-io" /S
	xcopy socket.io-client "$(LUA_LUADIR)/socket-io/socket.io-client" /S

clean:
#	rm src/fastcgi/lfcgi.o src/fastcgi/lfcgi.so

